### ISSUE TITLE
Change to emulated

### ISSUE THREAD

**Issue by PCandeias** [sweng-epfl/jenkins-setup#1]
https://github.com/sweng-epfl/jenkins-setup/blob/00356e4a6539c3c622bc74344c5383b608478da0/android-avd/emulator.sh#L22

Would it be possible to change this line to this:
-no-audio -camera-front emulated -camera-back emulated -screen no-touch \

as mentionned in the article:
https://developer.android.com/studio/run/emulator-commandline.html

Some of our tests rely on a Camera existing in the application and this would greatly help us, as mentioned in the last meeting @necto 

I tested it locally and it seems to work fine.

Thanks

**Comment by SolalPirelli** [comment]
It might work. I'll try it tonight.

Unfortunately, the one thing I've learned while creating these scripts is that the Google official docs is often misleading, incomplete, or outright wrong, and the emulator may not work or be stuck in a boot loop depending on these kinds of things. :s

**Comment by SolalPirelli** [comment]
OK, it seems to work with emulated cameras. (I built your master on it)
